### ISSUE TITLE
null al buscar el UID

### ISSUE THREAD

**Issue by 5rzmz8odb** [ezruneko/masvoz-sagemcom-fast-5355-hacks#1]
Hola @ezruneko gran aporte

Conoces otra manera de obtener el UID para acceder por ssh si $.xmo.getValuesTree("Device/UserAccounts/Users"); devuelve null?

Gracias

**Comment by ezruneko** [comment]
¿Que operador tienes y que version del software tiene tu router?

**Comment by 5rzmz8odb** [comment]
Yoigo + SG3V10000301

**Comment by javieritis** [comment]
Si, correcto, devuelve null al realizar el comando para obtener los usuarios.

<img width="363" alt="Screenshot 2021-11-04 at 12 59 35" src="https://user-images.githubusercontent.com/11956969/140309838-e087e502-5e3d-4d85-9ba5-6c83b0e1f55a.png">

**Comment by ezruneko** [comment]
Parece que vuestros firmware cuentan con otra version y esta parcheada como para obtener estos datos.
